### PR TITLE
Use editor debug component instead of duplicated code (see GN-3152)

### PR DESCRIPTION
**Pull request by benjay10**
This plugin now uses the debug component from the ember-rdfa-editor instead of duplicating code. As of now this depends on release 0.50.0-beta.6 of the editor.
Was tested, but please, test the build and its dependencies as a double check.

### CODE REVIEW

**Review by nvdk — CHANGES_REQUESTED** [review]
edit: reviewed incorrect PR

**Comment by benjay10** [comment]
I have never seen the component in action, not even on an older version. If I remember correctly, an older commit complained about `executeQuery` not being a function.
The build failure due to tests not not passing is because of a default test not setting up the correct arguments to render the component correctly, and should not affect the functionality of the plugin, nor the use of the new debug component.

**Comment by abeforgit** [comment]
yeah this branch was always a bit of an experimental one and was made before the plugin api stabilized

**Comment by benjay10** [comment]
It works. It needed the proper RDFa context. By putting a `div` with `typeof="besluit:BehandelingVanAgendapunt"` in the editor, the plugin correctly triggers, because the templates it finds can only be used in that context. Also keep in mind that you need to test this plugin with a working instance of the backend of GN and start this dummy app with (e.g.) `ember serve --proxy http://localhost/`.

**Comment by abeforgit** [comment]
This should do it, once CI completes, you can merge

**Pull request merged**
